import Link from 'next/link';
import { client } from '@/sanity/lib/client'; // Automatically generated by your setup

// Define the shape of our Sanity data
interface Job {
    _id: string;
    title: string;
    location: string;
    department: string;
    type: string;
}

// Make the component async so it can fetch data directly
export default async function OpenPositions() {
    // Fetch all published jobs from your Sanity database
    const query = `*[_type == "job"] | order(_createdAt desc)`;
    const jobs: Job[] = await client.fetch(query);

    return (
        <section className="w-full py-24 px-8 max-w-5xl mx-auto">
            <div className="flex flex-col md:flex-row md:items-end justify-between mb-12">
                <h2 className="text-3xl font-serif">Open Roles</h2>
                <p className="text-xs text-gray-500 mt-4 md:mt-0">Don't see a fit? Send your resume to careers@elante.in</p>
            </div>

            <div className="flex flex-col">
                {jobs.length === 0 ? (
                    <p className="text-gray-400 text-sm py-4">No open positions at the moment. Check back soon!</p>
                ) : (
                    jobs.map((job) => (
                        <div key={job._id} className="group border-t border-gray-800 py-6 flex flex-col md:flex-row justify-between items-start md:items-center hover:bg-[#161f30] transition-colors px-4 -mx-4 cursor-pointer">

                            <div className="mb-4 md:mb-0">
                                <h3 className="text-lg font-serif text-gray-200 group-hover:text-white mb-2">{job.title}</h3>
                                <div className="flex flex-wrap gap-3 text-[10px] text-gray-500 uppercase tracking-widest font-mono">
                                    <span className="flex items-center gap-1"><span className="w-3">📍</span> {job.location}</span>
                                    {job.department && (
                                        <>
                                            <span>•</span>
                                            <span>{job.department}</span>
                                        </>
                                    )}
                                    {job.type && (
                                        <>
                                            <span>•</span>
                                            <span>{job.type}</span>
                                        </>
                                    )}
                                </div>
                            </div>

                            <Link href="#" className="border border-gray-700 px-6 py-2 text-[10px] font-bold uppercase tracking-widest group-hover:border-white group-hover:text-black group-hover:bg-white transition-all whitespace-nowrap">
                                Apply &rarr;
                            </Link>
                        </div>
                    ))
                )}
                <div className="border-t border-gray-800"></div>
            </div>
        </section>
    );
}